FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
COPY apps ./apps
COPY packages ./packages

RUN npm ci
RUN npm run build --workspace @mypos/customer-qr

EXPOSE 3000

CMD ["npm", "run", "start", "--workspace", "@mypos/customer-qr"]
