FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY apps ./apps
COPY packages ./packages

RUN npm ci
RUN npm run build --workspace @mypos/pos-console

FROM nginx:1.27-alpine

COPY deploy/nginx-spa.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/pos-console/dist /usr/share/nginx/html

EXPOSE 80
