FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY apps ./apps
COPY packages ./packages
COPY prisma ./prisma

RUN npm ci
RUN npm run db:generate

EXPOSE 4000

CMD ["npm", "run", "start", "--workspace", "@mypos/api"]
